import type { Template } from "./types";

// Built-in templates. Each contributes a restrained design theme to the deck.
// Kept deliberately neutral and editorial — no glowing gradients.
export const BUILT_IN_TEMPLATES: Template[] = [
  {
    id: "tpl_editorial",
    name: "Editorial",
    category: "General",
    description:
      "Serif headlines, generous whitespace, left-aligned. Reads like a considered document.",
    sourceType: "built-in",
    theme: {
      accent: "#C2410C",
      surface: "#FAF7F2",
      ink: "#1C1917",
      fontFamily: "serif",
      character: "Warm · editorial",
      backgroundStyle: "solid",
      headlineWeight: 800,
      headlineLetterSpacing: -0.03,
      headlineSizeMultiplier: 1.1,
      decorationStyle: "minimal",
      cardStyle: "bordered",
      accentLineWeight: 3,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "tpl_boardroom",
    name: "Boardroom",
    category: "Executive",
    description:
      "Restrained and formal. Built for exec reviews, QBRs, and board updates.",
    sourceType: "built-in",
    theme: {
      accent: "#14532D",
      surface: "#F8FAF8",
      ink: "#0F1F13",
      fontFamily: "serif",
      character: "Formal · muted green",
      backgroundStyle: "solid",
      headlineWeight: 700,
      headlineLetterSpacing: -0.02,
      decorationStyle: "corners",
      cardStyle: "flat",
      accentLineWeight: 2,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "tpl_sales",
    name: "Sales Motion",
    category: "Sales",
    description:
      "Punchy structure for pitches and proposals. Clear problem → solution → ask.",
    sourceType: "built-in",
    theme: {
      accent: "#DC2626",
      surface: "#FFFFFF",
      ink: "#0F0F0F",
      fontFamily: "sans",
      character: "Direct · confident",
      backgroundStyle: "solid",
      headlineWeight: 900,
      headlineLetterSpacing: -0.04,
      headlineSizeMultiplier: 1.2,
      decorationStyle: "geometric",
      cardStyle: "filled",
      accentLineWeight: 4,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "tpl_consulting",
    name: "Consulting Brief",
    category: "Consulting",
    description:
      "Analytical layout for findings and recommendations. Structured and dense.",
    sourceType: "built-in",
    theme: {
      accent: "#1E3A5F",
      surface: "#F9FAFB",
      ink: "#111827",
      fontFamily: "sans",
      character: "Analytical · ink",
      backgroundStyle: "solid",
      headlineWeight: 700,
      headlineLetterSpacing: -0.02,
      decorationStyle: "lines",
      cardStyle: "bordered",
      accentLineWeight: 1,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "tpl_startup",
    name: "Startup Update",
    category: "Startup",
    description:
      "For investor updates and all-hands. Momentum-forward but not hypey.",
    sourceType: "built-in",
    theme: {
      accent: "#0D9488",
      surface: "#F0FDFA",
      ink: "#134E4A",
      fontFamily: "sans",
      character: "Modern · teal",
      backgroundStyle: "gradient",
      backgroundGradient: "linear-gradient(135deg, #0D9488 0%, #0E7490 100%)",
      headlineWeight: 800,
      decorationStyle: "circles",
      cardStyle: "elevated",
      accentLineWeight: 2,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "tpl_mono",
    name: "Monochrome",
    category: "General",
    description:
      "Black, white, and one line weight. Maximum focus on the words.",
    sourceType: "built-in",
    theme: {
      accent: "#000000",
      surface: "#FFFFFF",
      ink: "#000000",
      fontFamily: "sans",
      character: "Minimal · black",
      backgroundStyle: "solid",
      headlineWeight: 900,
      headlineLetterSpacing: -0.05,
      headlineSizeMultiplier: 1.3,
      decorationStyle: "none",
      cardStyle: "bordered",
      accentLineWeight: 1,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "midnight-navy",
    name: "Midnight Navy",
    category: "Corporate",
    description:
      "Deep navy authority with gold accents. Board rooms and investor decks.",
    sourceType: "built-in",
    theme: {
      accent: "#D4A853",
      surface: "#F8F7F4",
      ink: "#0D1B2A",
      fontFamily: "sans",
      character: "Authority",
      backgroundStyle: "dark-gradient",
      backgroundGradient:
        "linear-gradient(160deg, #0D1B2A 0%, #162032 50%, #0A1520 100%)",
      headlineWeight: 800,
      headlineLetterSpacing: -0.03,
      decorationStyle: "geometric",
      cardStyle: "elevated",
      accentLineWeight: 2,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "cobalt-pro",
    name: "Cobalt Pro",
    category: "Sales",
    description:
      "Bright cobalt energy. Perfect for sales pitches and product launches.",
    sourceType: "built-in",
    theme: {
      accent: "#2B4EFF",
      surface: "#FFFFFF",
      ink: "#0F1729",
      fontFamily: "sans",
      character: "Energetic",
      backgroundStyle: "gradient",
      backgroundGradient: "linear-gradient(135deg, #1E3BCC 0%, #2B4EFF 100%)",
      headlineWeight: 900,
      headlineLetterSpacing: -0.04,
      headlineSizeMultiplier: 1.15,
      decorationStyle: "circles",
      cardStyle: "filled",
      accentLineWeight: 3,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "forest-executive",
    name: "Forest Executive",
    category: "Consulting",
    description:
      "Deep forest green with cream. Sophisticated consulting and strategy.",
    sourceType: "built-in",
    theme: {
      accent: "#1B4332",
      surface: "#F9F6EF",
      ink: "#1A2B1E",
      fontFamily: "serif",
      character: "Refined",
      backgroundStyle: "solid",
      headlineWeight: 700,
      headlineLetterSpacing: -0.02,
      decorationStyle: "minimal",
      cardStyle: "flat",
      accentLineWeight: 2,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "pure-slate",
    name: "Pure Slate",
    category: "Tech",
    description:
      "Charcoal slate with electric cyan. Modern tech and SaaS decks.",
    sourceType: "built-in",
    theme: {
      accent: "#00B4D8",
      surface: "#F4F6F8",
      ink: "#1C2333",
      fontFamily: "sans",
      character: "Modern",
      backgroundStyle: "dark-gradient",
      backgroundGradient: "linear-gradient(160deg, #1C2333 0%, #0F1929 100%)",
      headlineWeight: 800,
      headlineLetterSpacing: -0.03,
      decorationStyle: "lines",
      cardStyle: "elevated",
      accentLineWeight: 2,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "crimson-authority",
    name: "Crimson Authority",
    category: "Corporate",
    description: "Deep crimson with white space. Confident and commanding.",
    sourceType: "built-in",
    theme: {
      accent: "#9B1D20",
      surface: "#FAFAFA",
      ink: "#1A0A0B",
      fontFamily: "sans",
      character: "Bold",
      backgroundStyle: "dark-gradient",
      backgroundGradient: "linear-gradient(160deg, #1A0A0B 0%, #2D0F11 100%)",
      headlineWeight: 900,
      headlineLetterSpacing: -0.04,
      headlineSizeMultiplier: 1.2,
      decorationStyle: "geometric",
      cardStyle: "filled",
      accentLineWeight: 3,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "ocean-deep",
    name: "Ocean Deep",
    category: "Consulting",
    description:
      "Rich teal with warm white. Research reports and annual reviews.",
    sourceType: "built-in",
    theme: {
      accent: "#0D6E6E",
      surface: "#F7F9F9",
      ink: "#0A2E2E",
      fontFamily: "sans",
      character: "Calm",
      backgroundStyle: "gradient",
      backgroundGradient: "linear-gradient(135deg, #0A2E2E 0%, #0D6E6E 100%)",
      headlineWeight: 800,
      decorationStyle: "circles",
      cardStyle: "elevated",
      accentLineWeight: 2,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "obsidian",
    name: "Obsidian",
    category: "Creative",
    description: "Near-black with bright amber. Premium and high-contrast.",
    sourceType: "built-in",
    theme: {
      accent: "#F59E0B",
      surface: "#F5F5F5",
      ink: "#0C0C0C",
      fontFamily: "sans",
      character: "Premium",
      backgroundStyle: "dark-gradient",
      backgroundGradient: "linear-gradient(160deg, #0C0C0C 0%, #1A1A1A 100%)",
      headlineWeight: 800,
      headlineLetterSpacing: -0.03,
      decorationStyle: "minimal",
      cardStyle: "elevated",
      accentLineWeight: 2,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "purple-reign",
    name: "Purple Reign",
    category: "Creative",
    description:
      "Rich violet with soft lavender tints. Innovation and vision decks.",
    sourceType: "built-in",
    theme: {
      accent: "#6D28D9",
      surface: "#FAF9FF",
      ink: "#1E1030",
      fontFamily: "sans",
      character: "Visionary",
      backgroundStyle: "gradient",
      backgroundGradient:
        "linear-gradient(135deg, #1E1030 0%, #3B1F6E 50%, #4C1D95 100%)",
      headlineWeight: 800,
      headlineLetterSpacing: -0.03,
      decorationStyle: "circles",
      cardStyle: "elevated",
      accentLineWeight: 2,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "desert-sand",
    name: "Desert Sand",
    category: "Sales",
    description: "Warm sand with terracotta. Human, warm, and memorable.",
    sourceType: "built-in",
    theme: {
      accent: "#C26B3B",
      surface: "#FBF6EF",
      ink: "#2C1A0E",
      fontFamily: "serif",
      character: "Warm",
      backgroundStyle: "solid",
      headlineWeight: 700,
      headlineLetterSpacing: -0.02,
      decorationStyle: "minimal",
      cardStyle: "flat",
      accentLineWeight: 2,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
  {
    id: "arctic-white",
    name: "Arctic White",
    category: "Corporate",
    description:
      "Ultra-clean white with ice blue. Minimalist and editorial.",
    sourceType: "built-in",
    theme: {
      accent: "#4A90D9",
      surface: "#FFFFFF",
      ink: "#111827",
      fontFamily: "sans",
      character: "Minimal",
      backgroundStyle: "solid",
      headlineWeight: 700,
      decorationStyle: "none",
      cardStyle: "bordered",
      accentLineWeight: 1,
    },
    createdAt: "2025-01-01T00:00:00.000Z",
  },
];

export function getTemplate(
  id: string,
  extra: Template[] = [],
): Template | undefined {
  return [...BUILT_IN_TEMPLATES, ...extra].find((t) => t.id === id);
}

export const TEMPLATE_CATEGORIES = [
  "All",
  "General",
  "Executive",
  "Sales",
  "Consulting",
  "Startup",
  "Corporate",
  "Tech",
  "Creative",
];
